/**
 * Chrome theme .zip generator.
 * Produces a Chrome extension theme with NTP world map background.
 */
import { readFileSync } from 'node:fs';
import { Resvg } from '@resvg/resvg-js';
import archiver from 'archiver';
import * as allFlags from 'country-flag-icons/string/3x2';

const FLAG_SVG = allFlags as Record<string, string>;

// SVG coordinates for countries missing from the world map (micro-states, islands)
const MISSING_COUNTRY_COORDS: Record<string, [number, number]> = {
  AD: [407.63, 415.64], AG: [257.42, 485.26], AQ: [404.02, 700.22],
  BB: [262.77, 495.84], BH: [523.95, 460.62], FJ: [814.84, 580.4],
  FM: [761.16, 511.62], GD: [257.7, 498.79],  KI: [814.34, 526.82],
  KN: [255.08, 484.45], LI: [426.69, 402.89], MC: [421.63, 412.27],
  MH: [810.11, 512.42], NR: [800.02, 533.37], PS: [487.6, 444.52],
  PW: [723.28, 511.37], SM: [433.57, 411.71], TL: [702.27, 556.21],
  TO: [808, 589.88],    TV: [814.84, 551.39], VA: [433.56, 417.29],
  WS: [805, 569.58],    XK: [453.6, 415.38],
};

const NTP_WIDTH = 1920;
const NTP_HEIGHT = 1080;

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [
    Number.parseInt(h.slice(0, 2), 16),
    Number.parseInt(h.slice(2, 4), 16),
    Number.parseInt(h.slice(4, 6), 16),
  ];
}

export interface ThemeInput {
  countryCode: string;
  name: string;
  mode: string;
  flagColors: string[];
  tokens: {
    bg: string; surface: string; text: string; mutedText: string;
    border: string; accent: string; accent2: string; accentText: string;
    link: string; focusRing: string;
  };
}

export interface ThemeAssets {
  mapSvgPath: string;
  fontPath: string;
}

/** Build Chrome theme manifest. */
function buildManifest(input: ThemeInput) {
  const { tokens } = input;
  return {
    manifest_version: 3,
    version: '1.0',
    name: `${input.name} - ${input.mode} Theme`,
    description: `Browser theme inspired by the flag of ${input.name}. Generated by flagtheme.com`,
    theme: {
      colors: {
        frame: hexToRgb(tokens.bg),
        frame_inactive: hexToRgb(tokens.bg),
        toolbar: hexToRgb(tokens.accent),
        tab_text: hexToRgb(tokens.accentText),
        tab_background_text: hexToRgb(tokens.text),
        bookmark_text: hexToRgb(tokens.accentText),
        ntp_background: hexToRgb(tokens.bg),
        ntp_text: hexToRgb(tokens.text),
        button_background: hexToRgb(tokens.surface),
      },
      images: {
        theme_ntp_background: 'images/ntp_background.png',
        theme_ntp_attribution: 'images/attribution.png',
      },
      properties: { ntp_background_alignment: 'center' },
    },
  };
}

/** Render NTP background PNG (world map with highlighted country). */
export function renderNtpBackground(input: ThemeInput, mapSvgRaw: string): Buffer {
  const { countryCode, flagColors, tokens } = input;

  const vbMatch = mapSvgRaw.match(/viewBox="([^"]+)"/);
  if (!vbMatch) throw new Error('No viewBox in map SVG');
  const [vbX, vbY, vbW, vbH] = vbMatch[1].split(' ').map(Number);

  const PAD_X = vbW * 0.08;
  const PAD_Y = vbH * 0.15;
  const nVbX = vbX - PAD_X, nVbY = vbY - PAD_Y;
  const nVbW = vbW + PAD_X * 2, nVbH = vbH + PAD_Y * 2;

  let svg = mapSvgRaw.replace(
    /<svg[^>]*>/,
    `<svg xmlns="http://www.w3.org/2000/svg" width="${NTP_WIDTH}" height="${NTP_HEIGHT}" viewBox="${nVbX} ${nVbY} ${nVbW} ${nVbH}">`,
  );

  const stops = flagColors
    .map((color, i) => {
      const offset = flagColors.length === 1 ? '50%' : `${Math.round((i / (flagColors.length - 1)) * 100)}%`;
      return `<stop offset="${offset}" stop-color="${color}"/>`;
    })
    .join('');

  const cid = countryCode.toLowerCase();
  const glowColor = flagColors.find(c => c !== '#FFFFFF' && c !== '#ffffff') || flagColors[0];

  const defs = `
<defs>
  <linearGradient id="fg" x1="0" y1="0" x2="0" y2="1">${stops}</linearGradient>
  <filter id="glow" x="-50%" y="-50%" width="200%" height="200%">
    <feGaussianBlur in="SourceGraphic" stdDeviation="4" result="blur"/>
    <feFlood flood-color="${glowColor}" flood-opacity="0.6" result="color"/>
    <feComposite in="color" in2="blur" operator="in" result="cb"/>
    <feGaussianBlur in="cb" stdDeviation="6" result="og"/>
    <feMerge><feMergeNode in="og"/><feMergeNode in="SourceGraphic"/></feMerge>
  </filter>
</defs>
<rect x="${nVbX}" y="${nVbY}" width="${nVbW}" height="${nVbH}" fill="${tokens.bg}"/>
<style>
  path,g path{fill:${tokens.border};opacity:.35;stroke:${tokens.surface};stroke-width:.3}
  #${cid},path#${cid},g#${cid}{filter:url(#glow)}
  #${cid} path,#${cid}.mainland,path#${cid}{fill:url(#fg);opacity:1;stroke:${tokens.accent};stroke-width:1}
  g#${cid} path{fill:url(#fg);opacity:1;stroke:${tokens.accent};stroke-width:1}
</style>`;

  svg = svg.replace(/(>)/, '>' + defs);

  // Micro-states: embed real SVG flag
  const coords = MISSING_COUNTRY_COORDS[countryCode];
  if (coords) {
    const [cx, cy] = coords;
    const FW = 30, FH = 20;
    const flagSrc = FLAG_SVG[countryCode];
    if (flagSrc) {
      const inner = flagSrc.replace(/<svg[^>]*>/, '').replace(/<\/svg>/, '');
      svg = svg.replace('</svg>',
        `<g filter="url(#glow)">` +
        `<svg x="${cx - FW / 2}" y="${cy - FH / 2}" width="${FW}" height="${FH}" viewBox="0 0 513 342">${inner}</svg>` +
        `<rect x="${cx - FW / 2}" y="${cy - FH / 2}" width="${FW}" height="${FH}" fill="none" stroke="${tokens.accent}" stroke-width=".6" rx=".5"/>` +
        `</g></svg>`);
    }
  }

  const resvg = new Resvg(svg, { fitTo: { mode: 'width' as const, value: NTP_WIDTH } });
  return Buffer.from(resvg.render().asPng());
}

/** Render attribution PNG. */
export function renderAttribution(mutedTextColor: string, fontData: Buffer): Buffer {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="160" height="24">
  <text x="4" y="17" font-family="Noto Sans" font-size="14" fill="${mutedTextColor}" opacity="0.8">flagtheme.com</text>
</svg>`;
  const resvg = new Resvg(svg, {
    font: { fontBuffers: [fontData], loadSystemFonts: false },
    fitTo: { mode: 'original' as const },
  });
  return Buffer.from(resvg.render().asPng());
}

/** Generate a Chrome theme .zip as a Buffer. */
export async function generateChromeThemeZip(input: ThemeInput, assets: ThemeAssets): Promise<Buffer> {
  const mapSvgRaw = readFileSync(assets.mapSvgPath, 'utf-8');
  const fontData = readFileSync(assets.fontPath);

  const manifest = buildManifest(input);
  const ntpPng = renderNtpBackground(input, mapSvgRaw);
  const attrPng = renderAttribution(input.tokens.mutedText, fontData);

  return new Promise<Buffer>((ok, fail) => {
    const chunks: Buffer[] = [];
    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('data', (chunk: Buffer) => chunks.push(chunk));
    archive.on('end', () => ok(Buffer.concat(chunks)));
    archive.on('error', fail);

    archive.append(JSON.stringify(manifest, null, 2), { name: 'manifest.json' });
    archive.append(ntpPng, { name: 'images/ntp_background.png' });
    archive.append(attrPng, { name: 'images/attribution.png' });

    archive.finalize();
  });
}
